//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.1433
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemCreator.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class winFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal winFormStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ItemCreator.Resources.winFormStrings", typeof(winFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Merecs ItemCreator for Dawn of Light ähnelt.
        /// </summary>
        internal static string application_name {
            get {
                return ResourceManager.GetString("application_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete all assigned MobXLootTemplates of this LootTemplate? ähnelt.
        /// </summary>
        internal static string ask_delete_assigned_mobxloottemplates {
            get {
                return ResourceManager.GetString("ask_delete_assigned_mobxloottemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete assigned MobXLootTemplates ähnelt.
        /// </summary>
        internal static string ask_delete_assigned_mobxloottemplates_title {
            get {
                return ResourceManager.GetString("ask_delete_assigned_mobxloottemplates_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete this entry? ähnelt.
        /// </summary>
        internal static string ask_delete_entry {
            get {
                return ResourceManager.GetString("ask_delete_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete LootTemplate ähnelt.
        /// </summary>
        internal static string ask_delete_loot_template_title {
            get {
                return ResourceManager.GetString("ask_delete_loot_template_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete MobXLootTemplate ähnelt.
        /// </summary>
        internal static string ask_delete_mobxloottemplate_title {
            get {
                return ResourceManager.GetString("ask_delete_mobxloottemplate_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File &quot;base.xml&quot; no found, please reinstall application! ähnelt.
        /// </summary>
        internal static string error_basefile_not_found {
            get {
                return ResourceManager.GetString("error_basefile_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This Item does not exist in the Database! ähnelt.
        /// </summary>
        internal static string error_item_not_in_database {
            get {
                return ResourceManager.GetString("error_item_not_in_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This Keyname is used by &quot;{0}&quot; ähnelt.
        /// </summary>
        internal static string error_itemkey_in_use_by {
            get {
                return ResourceManager.GetString("error_itemkey_in_use_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string error_messagebox_title {
            get {
                return ResourceManager.GetString("error_messagebox_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You need to set a Keyname! ähnelt.
        /// </summary>
        internal static string error_no_itemkeyname {
            get {
                return ResourceManager.GetString("error_no_itemkeyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You need to set an Itemname! ähnelt.
        /// </summary>
        internal static string error_no_itemname {
            get {
                return ResourceManager.GetString("error_no_itemname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You need to set a Model ID! ähnelt.
        /// </summary>
        internal static string error_no_model_id {
            get {
                return ResourceManager.GetString("error_no_model_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while reading &quot;base.xml&quot;, please reinstall application! ähnelt.
        /// </summary>
        internal static string error_reading_basefile {
            get {
                return ResourceManager.GetString("error_reading_basefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfull connected! ähnelt.
        /// </summary>
        internal static string message_connection_successfull {
            get {
                return ResourceManager.GetString("message_connection_successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LootTemplates needed! ähnelt.
        /// </summary>
        internal static string message_loot_templates_needed {
            get {
                return ResourceManager.GetString("message_loot_templates_needed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No assigned mobs found! ähnelt.
        /// </summary>
        internal static string message_no_assigned_mobs {
            get {
                return ResourceManager.GetString("message_no_assigned_mobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Itemkeyname is set! ähnelt.
        /// </summary>
        internal static string message_no_itemkeyname {
            get {
                return ResourceManager.GetString("message_no_itemkeyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No LootTemplates found! ähnelt.
        /// </summary>
        internal static string message_no_loottemplates {
            get {
                return ResourceManager.GetString("message_no_loottemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MySQL-support is not enabled! ähnelt.
        /// </summary>
        internal static string message_no_mysql_support {
            get {
                return ResourceManager.GetString("message_no_mysql_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Item ähnelt.
        /// </summary>
        internal static string new_item {
            get {
                return ResourceManager.GetString("new_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} MobXLootTemplates deleted! ähnelt.
        /// </summary>
        internal static string num_deleted_mobxloottemplates {
            get {
                return ResourceManager.GetString("num_deleted_mobxloottemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are new preferences options. Please check options and save. ähnelt.
        /// </summary>
        internal static string preferences_new_options {
            get {
                return ResourceManager.GetString("preferences_new_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save &quot;{0}&quot;? ähnelt.
        /// </summary>
        internal static string save_file_with_filename {
            get {
                return ResourceManager.GetString("save_file_with_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Would you like to save this Item? ähnelt.
        /// </summary>
        internal static string save_item_ask {
            get {
                return ResourceManager.GetString("save_item_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die save Item ähnelt.
        /// </summary>
        internal static string save_item_title {
            get {
                return ResourceManager.GetString("save_item_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die checking MySQL settings ... ähnelt.
        /// </summary>
        internal static string splash_checking_mysql_settings {
            get {
                return ResourceManager.GetString("splash_checking_mysql_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die checking for new versions ... ähnelt.
        /// </summary>
        internal static string splash_checking_versions {
            get {
                return ResourceManager.GetString("splash_checking_versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die loading ... ähnelt.
        /// </summary>
        internal static string splash_loading {
            get {
                return ResourceManager.GetString("splash_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die loading preferences ... ähnelt.
        /// </summary>
        internal static string splash_loading_preferences {
            get {
                return ResourceManager.GetString("splash_loading_preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die loading XML ... ähnelt.
        /// </summary>
        internal static string splash_loading_xml {
            get {
                return ResourceManager.GetString("splash_loading_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die starting application ähnelt.
        /// </summary>
        internal static string splash_starting {
            get {
                return ResourceManager.GetString("splash_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error! ähnelt.
        /// </summary>
        internal static string sql_error {
            get {
                return ResourceManager.GetString("sql_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No rows affected ähnelt.
        /// </summary>
        internal static string sql_no_affected_rows {
            get {
                return ResourceManager.GetString("sql_no_affected_rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die running ... ähnelt.
        /// </summary>
        internal static string sql_running {
            get {
                return ResourceManager.GetString("sql_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfull! ähnelt.
        /// </summary>
        internal static string sql_successfull {
            get {
                return ResourceManager.GetString("sql_successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die check done! ähnelt.
        /// </summary>
        internal static string updater_check_done {
            get {
                return ResourceManager.GetString("updater_check_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die checking versions ... ähnelt.
        /// </summary>
        internal static string updater_checking_version {
            get {
                return ResourceManager.GetString("updater_checking_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading &quot;{0}&quot; ... ähnelt.
        /// </summary>
        internal static string updater_downloading_file {
            get {
                return ResourceManager.GetString("updater_downloading_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading ItemCreator-Files ... ähnelt.
        /// </summary>
        internal static string updater_downloading_files {
            get {
                return ResourceManager.GetString("updater_downloading_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error! ähnelt.
        /// </summary>
        internal static string updater_error {
            get {
                return ResourceManager.GetString("updater_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ItemCreator Updater needs to be started! ähnelt.
        /// </summary>
        internal static string updater_need_start {
            get {
                return ResourceManager.GetString("updater_need_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New versions of Application or Databases are available! ähnelt.
        /// </summary>
        internal static string updater_new_versions_are_available {
            get {
                return ResourceManager.GetString("updater_new_versions_are_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Versions available ähnelt.
        /// </summary>
        internal static string updater_new_versions_are_available_title {
            get {
                return ResourceManager.GetString("updater_new_versions_are_available_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ItemCreator needs to be restarted! ähnelt.
        /// </summary>
        internal static string updater_restart_app {
            get {
                return ResourceManager.GetString("updater_restart_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update complete! ähnelt.
        /// </summary>
        internal static string updater_update_complete {
            get {
                return ResourceManager.GetString("updater_update_complete", resourceCulture);
            }
        }
    }
}
